# This build script is meant for spinning up a known-good development 
# environment on a VM. Running 'vagrant up' in this directory will ultimately
# invoke this.
---

- hosts: all
  tasks:

    - name: install system packages
      apt: state=present name={{ item }}
      with_items:
        - apt-file
        - cowsay
        - git
        - libpq-dev
        - make
        - nginx
        - nodejs
        - postgresql
        - python-psycopg2
        - redis-server
        - redis-tools
        - qt4-default
        - qt4-qmake
        - redis-server
        - redis-tools
        - ruby
        - ruby-dev
        - xvfb

    ## Postgres Setup ##

    - name: ensure dev superuser account exists
      postgresql_user: name=postgres password=postgres role_attr_flags=SUPERUSER
      sudo: yes
      sudo_user: postgres

    - name: put the environment file into place, providing db config
      file: src=/vagrant/.env.example dest=/vagrant/.env state=link

    - name: put dev database username into the environment file
      lineinfile: dest=/vagrant/.env 
                  line="DB_USERNAME=postgres" 
                  regexp=^DB_USERNAME

    - name: put dev password into the environment file
      lineinfile: dest=/vagrant/.env
                  line="DB_PASSWORD=postgres" 
                  regexp=^DB_PASSWORD

    - name: ensure test database exists
      postgresql_db: name=mom-test
      sudo: yes
      sudo_user: postgres

    ## Dovetail with ./bin/setup ##

    - name: run the setup script (includes automated tests)
      shell: xvfb-run -a /vagrant/bin/setup
